### ISSUE TITLE
Plan for release?

### ISSUE THREAD

**Issue by vsoch** [danger89/fake-useragent#1]
hiya! I was using the original of this library, and I also am worried that the main maintainer is OK. For the time being I'm going to try using this fork - do you have any plans for an official release (e.g., on pypi?) thank you!

**Comment by MattDMo** [comment]
See the conversation at https://github.com/hellysmile/fake-useragent/pull/110 for some background and my most recent comment on a path forward.

**Comment by vsoch** [comment]
Thank you!
