### ISSUE TITLE
Heroku app 0.1.12 HTTP error 404

### ISSUE THREAD

**Issue by scmanjarrez** [danger89/fake-useragent#10]
Hi, do you own the [fake-useragent herokuapp](https://fake-useragent.herokuapp.com/)? If yes, can you update the endpoint for version 0.1.12? The URL in the current version is pointing to https://fake-useragent.herokuapp.com/browsers/0.1.12, however, it's returning error 404. If not, can you downgrade to version 0.1.11 (the last available in herokuapp)?

**Comment by danger89** [comment]
If you right. This is no longer working. I fixed the file format and cache server as well with the latest release (`v0.1.13` tag).

See also master branch: https://github.com/danger89/fake-useragent
