### ISSUE TITLE
fake_useragent.errors.FakeUserAgentError: No browsers version found for Chrome

### ISSUE THREAD

**Issue by ShiGhost** [danger89/fake-useragent#3]
Stopped working, the error `fake_useragent.errors.FakeUserAgentError: No browsers version found for Chrome`

**Comment by sgerodes** [comment]
@danger89 please merge this one

**Comment by danger89** [comment]
But https://github.com/danger89/fake-useragent/issues/3#issuecomment-1214765626  pull request is closed? Why?
